rack
Ajiexwel4/Codebreaker_rack pull request #1
Opened 2016-12-16 19:06 UTC by Ajiexwel4

2016-12-18 21:52 UTC, Alfarlost requested changes
Also some specs, please

2016-12-18 21:52 UTC, Alfarlost commented on lib/modules/marker.rb
> +      @player_code.to_s.chars.to_a.map.with_index { |num, index| '+' if num == @secret_code[index] }.compact.size
try to stick to max 120 chars per line convention. dat is really hard to read such long lines

2016-12-18 21:52 UTC, Alfarlost commented on lib/modules/marker.rb
> +        '+' * pluses + '-' * (minuses - pluses)
maybe, it is better to incapsulate multiplication logic inside methods pluses and munuses, if you use them only for generating response strings.
e.x. pluses method will return string with right amount of pluseses and the same with minuses.
now they return some random numbers

2016-12-18 21:52 UTC, Alfarlost commented on lib/modules/marker.rb
> +      if win?
to avoid using elseif you can just return congratualtions if win?

2016-12-18 21:52 UTC, Alfarlost commented on lib/racker.rb
> +  def path_score_file
there is a small mistake in method naming, should be score_file_path.

2016-12-19 08:16 UTC, Ajiexwel4 commented on lib/modules/marker.rb
> +      if win?
No, I can not. This logic assumed 3 aspects of game: win, game over, marking. It maybe possible if I using nested 'if', but I think that 'elsif' is better.

2017-01-11 10:47 UTC, merged